// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeSnippet: typeof import('./src/components/CodeSnippet.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    DropDownFile: typeof import('./src/components/DropDownFile.vue')['default']
    DropDownFolder: typeof import('./src/components/DropDownFolder.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    IIonic: typeof import('./src/components/icons/IIonic.vue')['default']
    Ijavascript: typeof import('./src/components/icons/IJavascript.vue')['default']
    IJavascript: typeof import('./src/components/icons/IJavascript.vue')['default']
    INextjs: typeof import('./src/components/icons/INextjs.vue')['default']
    INuxt: typeof import('./src/components/icons/INuxt.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheets: typeof import('./src/components/Sheets.vue')['default']
    SheetsMobile: typeof import('./src/components/SheetsMobile.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TransitionDrop: typeof import('./src/components/transitions/TransitionDrop.vue')['default']
  }
}
